//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaGaan.BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dieren
    {
        public Dieren()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string naam { get; set; }
        public string geslacht { get; set; }
        public string soort { get; set; }
        public int voerId { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
        public virtual VoerSchema VoerSchema { get; set; }
    }
}
