//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaGaan.BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evenement
    {
        public Evenement()
        {
            this.Inschrijving = new HashSet<Inschrijving>();
        }
    
        public int Id { get; set; }
        public string naam { get; set; }
        public decimal prijs { get; set; }
        public int aantalDeelnemers { get; set; }
        public Nullable<int> maxDeelnemers { get; set; }
        public string beschrijving { get; set; }
    
        public virtual ICollection<Inschrijving> Inschrijving { get; set; }
    }
}
