//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaGaan.BU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inkoop
    {
        public Inkoop()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string aantal { get; set; }
        public string beschrijving { get; set; }
        public int productId { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
    }
}
