//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaGaan.BU
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dieren> DierenSet { get; set; }
        public virtual DbSet<MedewerkerRooster> MedewerkerRoosterSet { get; set; }
        public virtual DbSet<Video> VideoSet1 { get; set; }
        public virtual DbSet<Inschrijving> InschrijvingSet1 { get; set; }
        public virtual DbSet<Verkoop> VerkoopSet1 { get; set; }
        public virtual DbSet<Evenement> EvenementSet1 { get; set; }
        public virtual DbSet<Medewerkers> MedewerkersSet1 { get; set; }
        public virtual DbSet<VoerSchema> VoerSchemaSet1 { get; set; }
        public virtual DbSet<Foto> FotoSet1 { get; set; }
        public virtual DbSet<Openingstijden> OpeningstijdenSet { get; set; }
        public virtual DbSet<Winkel> WinkelSet { get; set; }
        public virtual DbSet<Inkoop> InkoopSet { get; set; }
        public virtual DbSet<Product> ProductSet { get; set; }
    }
}
