//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinderboerderij_Lama_Gaan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Dieren = new HashSet<Dieren>();
        }
    
        public int Id { get; set; }
        public string naam { get; set; }
        public decimal prijs { get; set; }
        public int bestelEenheid { get; set; }
        public int voorraad { get; set; }
        public string afkomst { get; set; }
    
        public virtual ICollection<Dieren> Dieren { get; set; }
        public virtual Verkoop Verkoop { get; set; }
        public virtual Inkoop Inkoop { get; set; }
        public virtual VoerSchema VoerSchema { get; set; }
    }
}
