//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinderboerderij_Lama_Gaan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verkoop
    {
        public Verkoop()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public int productId { get; set; }
        public int winkelId { get; set; }
        public int aantal { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
        public virtual Winkel Winkel { get; set; }
    }
}
