//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinderboerderij_Lama_Gaan
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoerSchema
    {
        public VoerSchema()
        {
            this.Medewerkers = new HashSet<Medewerkers>();
            this.Dieren = new HashSet<Dieren>();
            this.Product = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public int voerId { get; set; }
        public int dierenId { get; set; }
        public string dag { get; set; }
        public System.TimeSpan tijd { get; set; }
        public int medewerkersId { get; set; }
    
        public virtual ICollection<Medewerkers> Medewerkers { get; set; }
        public virtual ICollection<Dieren> Dieren { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
